version: '3.9'

services:
  therapy_js:
    container_name: therapy_js
    image: node:14
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8005:8000"  # Проброс порта приложения на хост-машину
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - .:/app
    networks:
      - sirius_network
    depends_on:
      - postgres
    command: ["npm", "start"]

  postgres:
    container_name: therapy_postgres
    image: library/postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sirius
      POSTGRES_DB: therapy
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"  # Проброс порта PostgreSQL на хост-машину
    networks:
      - sirius_network

volumes:
  postgres_data:
networks:
  sirius_network:
    external: True